import type { Metadata } from "next";
import "./globals.css";
import UiLibraryProvider from "@/src/providers/UiLibraryProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Red Things",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <UiLibraryProvider>{children}</UiLibraryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
